name: Publish Preview

# Controls when the workflow will run
on:
  push:
    branches: [ "preview" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with: 
          repository: BrewSleeDerby/scoreboard
          ref: preview

      - name: setup nodes
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
      
      - name: build
        working-directory: ./app
        run: |
          npm ci
          npm build

      - name: upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./app/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
